### ISSUE TITLE
starting server failed

### ISSUE THREAD

**Issue by zhengbao** [xudafeng/startserver#22]
<<WARN>> : Get remote update info failed.
<<INFO>> : Running at http://0.0.0.0:8080

![image](https://cloud.githubusercontent.com/assets/1736166/20700587/1e6fa8fa-b649-11e6-8da6-9b7a330031f9.png)
![image](https://cloud.githubusercontent.com/assets/1736166/20700717/f4a3b4f2-b649-11e6-8153-74a4018305cf.png)

**Comment by xudafeng** [comment]
npm i startserver -g
